# Generated by Django 5.0.7 on 2024-07-22 20:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centres', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Commentaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texte', models.TextField()),
                ('date_commentaire', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Formation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
                ('niveau', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Personne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('prenom', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('telephone', models.CharField(blank=True, max_length=20, null=True)),
                ('date_naissance', models.DateField()),
                ('adresse', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SessionFormation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_debut', models.DateTimeField()),
                ('date_fin', models.DateTimeField()),
                ('lieu', models.CharField(max_length=255)),
            ],
        ),
        migrations.DeleteModel(
            name='Utilisateur',
        ),
        migrations.AddField(
            model_name='centreformation',
            name='adresse',
            field=models.CharField(default='Adresse par défaut', max_length=255),
        ),
        migrations.AddField(
            model_name='centreformation',
            name='code_postal',
            field=models.CharField(default='00000', max_length=20),
        ),
        migrations.AddField(
            model_name='centreformation',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='centreformation',
            name='pays',
            field=models.CharField(default='Non spécifié', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='centreformation',
            name='site_web',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='centreformation',
            name='telephone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='centreformation',
            name='ville',
            field=models.CharField(default='Non spécifié', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='centreformation',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='formation',
            name='centre_formation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='formations', to='centres.centreformation'),
        ),
        migrations.AddField(
            model_name='personne',
            name='centre_formation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='personnes', to='centres.centreformation'),
        ),
        migrations.AddField(
            model_name='commentaire',
            name='auteur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commentaires', to='centres.personne'),
        ),
        migrations.AddField(
            model_name='sessionformation',
            name='formateur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions', to='centres.personne'),
        ),
        migrations.AddField(
            model_name='sessionformation',
            name='formation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='centres.formation'),
        ),
        migrations.AddField(
            model_name='commentaire',
            name='session_formation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commentaires', to='centres.sessionformation'),
        ),
    ]
